-- Discovery history (BOUNTY_EARNINGS_PLAN.md Phase 2.2).
-- Observing a host records when it was seen. It does not activate the asset
-- and it does not authorize a request. discovery_runs stores each snapshot
-- so a later diff can name hosts that were not in the previous run.

ALTER TABLE assets ADD COLUMN IF NOT EXISTS first_seen timestamptz;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS last_seen timestamptz;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS confidence double precision;

DO $$ BEGIN
  ALTER TABLE assets ADD CONSTRAINT assets_source_check
    CHECK (source IS NULL OR source IN ('submitted', 'cert-transparency', 'passive-dns', 'subfinder', 'observed-link'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE assets ADD CONSTRAINT assets_confidence_check
    CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS discovery_runs (
  seq bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id text NOT NULL REFERENCES programs(id),
  started_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  finished_at timestamptz,
  hosts jsonb NOT NULL
);

DO $$ BEGIN
  ALTER TABLE discovery_runs ADD CONSTRAINT discovery_runs_hosts_array
    CHECK (jsonb_typeof(hosts) = 'array');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS discovery_runs_program_seq ON discovery_runs(program_id, seq DESC);
