version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
      time: '08:00'
      timezone: America/Chicago
    open-pull-requests-limit: 10
    groups:
      web-upstream-sources:
        patterns: ['*']
    commit-message:
      prefix: 'deps(web)'
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
